export enum ErrorCode {
    ApiKeyNotFound = 'API_KEY_NOT_FOUND',
    AuthDoesNotHavePasswordToValidate = 'AUTH_DOES_NOT_HAVE_PASSWORD_TO_VALIDATE',
    AuthNotFound = 'AUTH_NOT_FOUND',
    CantComparePasswords = 'CANT_COMPARE_PASSWORDS',
    CantGetValueFromOption = 'CANT_GET_VALUE_FROM_OPTION',
    DocuFileNotFound = 'DOC_FILE_NOT_FOUND',
    FolderNotFound = 'FOLDER_NOT_FOUND',
    InvalidApiKeyValue = 'INVALID_API_KEY_VALUE',
    InvalidId = 'INVALID_ID',
    InvalidLogin = 'INVALID_LOGIN',
    InvalidMimeType = 'INVALID_MIME_TYPE',
    InvalidPassword = 'INVALID_PASSWORD',
    InvalidPermission = 'INVALID_PERMISSION',
    InvalidSharedToken = 'INVALID_SHARED_TOKEN',
    InvalidToken = 'INVALID_TOKEN',
    SharedDocuFileNotFound = 'SHARED_DOC_FILE_NOT_FOUND',
    Unauthorized = 'UNAUTHORIZED',
    UserAlreadyExists = 'USER_ALREADY_EXISTS',
    UserNotFound = 'USER_NOT_FOUND',
    WrongPassword = 'WRONG_PASSWORD',
}